version: '2'
services:
  webserver:
    build: "./webserver/docker"
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    restart: on-failure
    depends_on:
      - "database"
    environment:
      - DBHOST=database
      - DBUSER=${DB_USER}
      - DBPASSWD=${DB_PASSWORD}
  database:
    image: "mariadb:10"
    environment:
      - MYSQL_DATABASE=tournament
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - backend
    volumes:
      - "mydata:/var/lib/mysql"
      - "./tournament_init.sql:/docker-entrypoint-initdb.d/01_init.sql:Z"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mydata:
