---
- hosts: frontend
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  tasks:
  - name: suppress initial raspberry user
    user:
      name: "{{ raspberry_initial_user }}"
      state: absent
      remove: yes

